-- jobs.lua
local jobs = {
    "Accountant", "Actor", "Actuary", "Ad Copywriter", "Aerospace Engineer",
    "Agricultural Engineer", "Air Traffic Controller", "Anesthesiologist", "Animator", "Anthropologist",
    "Application Developer", "Archaeologist", "Architect", "Art Director", "Artificial Intelligence Engineer",
    "Astronomer", "Athletic Trainer", "Audio Engineer", "Auditor", "Author",
    "Automotive Engineer", "Baker", "Bank Teller", "Barber", "Bartender",
    "Biomedical Engineer", "Biotechnologist", "Blacksmith", "Boilermaker", "Bookkeeper",
    "Botanist", "Brand Manager", "Brewmaster", "Broadcast Engineer", "Building Inspector",
    "Business Analyst", "Butcher", "Buyer", "Cabinetmaker", "Camera Operator",
    "Cardiologist", "Carpenter", "Cartographer", "Cell Biologist", "Ceramic Artist",
    "Chef", "Chemical Engineer", "Chemist", "Childcare Worker", "Chiropractor",
    "Civil Engineer", "Claims Adjuster", "Climatologist", "Clinical Psychologist", "Cloud Architect",
    "CNC Operator", "Comedian", "Commercial Pilot", "Commodity Trader", "Community Health Worker",
    "Computer Scientist", "Concierge", "Conservation Scientist", "Construction Manager", "Content Strategist",
    "Copywriter", "Corporate Lawyer", "Cosmetologist", "Costume Designer", "Counselor",
    "Court Reporter", "Creative Director", "Credit Analyst", "Criminologist", "Curator",
    "Customer Service Representative", "Cybersecurity Specialist", "Dairy Farmer", "Dance Instructor", "Data Analyst",
    "Database Administrator", "Dental Hygienist", "Dentist", "Dermatologist", "Desktop Publisher",
    "Detective", "Dietitian", "Digital Marketer", "Diplomat", "Director of Operations",
    "Dishwasher", "Diver", "DJ", "Documentary Filmmaker", "Dog Trainer",
    "Drafter", "Drama Teacher", "Driver", "Drone Operator", "Ecologist",
    "Economist", "Editor", "Education Consultant", "Electrical Engineer", "Electrician",
    "Electronics Technician", "Elementary School Teacher", "Embryologist", "Emergency Medical Technician",
    "Endocrinologist",
    "Energy Auditor", "Engineer", "English Teacher", "Entomologist", "Environmental Consultant",
    "Environmental Engineer", "Epidemiologist", "Event Planner", "Executive Assistant", "Exercise Physiologist",
    "Exterminator", "Fabricator", "Family Physician", "Fashion Designer", "FBI Agent",
    "Film Director", "Financial Advisor", "Firefighter", "Fisherman", "Fitness Trainer",
    "Florist", "Food Scientist", "Forensic Scientist", "Forklift Operator", "Game Designer",
    "Gardener", "Genetic Counselor", "Geographer", "Geologist", "Glass Blower",
    "Graphic Designer", "Guidance Counselor", "Hair Stylist", "Handyman", "Hazardous Materials Handler",
    "Healthcare Administrator", "Hearing Aid Specialist", "High School Teacher", "Historian", "Home Inspector",
    "Horticulturist", "Hotel Manager", "Human Resources Specialist", "HVAC Technician", "Illustrator",
    "Immigration Officer", "Industrial Designer", "Industrial Engineer", "Information Security Analyst",
    "Insurance Agent",
    "Interior Designer", "Interpreter", "Investment Banker", "IT Consultant", "Janitor",
    "Jeweler", "Journalist", "Judge", "Laboratory Technician", "Land Surveyor",
    "Landscape Architect", "Language Teacher", "Lawyer", "Librarian", "Life Coach",
    "Line Cook", "Linguist", "Loan Officer", "Locksmith", "Logistics Coordinator",
    "Machine Operator", "Magician", "Mail Carrier", "Maintenance Worker", "Makeup Artist",
    "Management Consultant", "Manufacturing Engineer", "Marine Biologist", "Market Research Analyst", "Marketing Manager",
    "Massage Therapist", "Materials Engineer", "Mathematician", "Mechanical Engineer", "Media Buyer",
    "Medical Assistant", "Medical Laboratory Technician", "Medical Transcriptionist", "Meteorologist", "Microbiologist",
    "Middle School Teacher", "Midwife", "Military Officer", "Miner", "Mobile App Developer",
    "Model", "Mortician", "Motion Graphics Designer", "Motorcycle Mechanic", "Museum Director",
    "Music Producer", "Music Teacher", "Nail Technician", "Network Administrator", "Neurologist",
    "News Anchor", "Nutritionist", "Occupational Therapist", "Oceanographer", "Office Manager",
    "Oncologist", "Ophthalmologist", "Optician", "Optometrist", "Oral Surgeon",
    "Organic Farmer", "Orthodontist", "Orthopedic Surgeon", "Painter", "Paralegal",
    "Park Ranger", "Pastry Chef", "Pathologist", "Pediatrician", "Personal Trainer",
    "Petroleum Engineer", "Pharmacist", "Pharmacologist", "Photographer", "Physical Therapist",
    "Physician Assistant", "Physicist", "Pilot", "Plumber", "Podiatrist",
    "Police Officer", "Political Scientist", "Postal Worker", "PR Specialist", "Preschool Teacher",
    "Priest", "Principal", "Private Investigator", "Product Manager", "Professor",
    "Programmer", "Project Manager", "Psychiatrist", "Psychologist", "Public Health Worker",
    "Public Relations Officer", "Publisher", "Quality Assurance Analyst", "Radiation Therapist", "Radio Broadcaster",
    "Real Estate Agent", "Receptionist", "Recreational Therapist", "Recruiter", "Registered Nurse",
    "Reporter", "Research Scientist", "Respiratory Therapist", "Restaurant Manager", "Retail Salesperson",
    "Roofer", "Safety Officer", "Sales Manager", "Sanitation Worker", "School Counselor",
    "Scientist", "Screenwriter", "Scuba Diver", "Sculptor", "Seamstress",
    "Secretary", "Security Guard", "Semi Truck Driver", "SEO Specialist", "Server",
    "Service Technician", "Sheet Metal Worker", "Sheriff", "Ship Captain", "Shoe Designer",
    "Social Media Manager", "Social Worker", "Software Developer", "Soil Scientist", "Sound Engineer",
    "Special Education Teacher", "Speech Therapist", "Sports Coach", "Statistician", "Stock Broker",
    "Stone Mason", "Structural Engineer", "Surgeon", "Surveyor", "Systems Analyst",
    "Tailor", "Taxi Driver", "Teacher Assistant", "Technical Writer", "Telecommunications Technician",
    "Telemarketer", "Television Producer", "Tennis Instructor", "Textile Designer", "Theater Director",
    "Therapist", "Tour Guide", "Town Planner", "Toy Designer", "Trader",
    "Training Coordinator", "Translator", "Transportation Planner", "Travel Agent", "Tutor",
    "TV Repair Technician", "UI/UX Designer", "Ultrasound Technician", "Underwriter", "Urban Planner",
    "Urologist", "Veterinarian", "Video Editor", "Video Game Developer", "Videographer",
    "Virologist", "Voice Actor", "Waiter", "Warehouse Manager", "Watchmaker",
    "Web Developer", "Wedding Planner", "Welder", "Wildlife Biologist", "Window Cleaner",
    "Wine Maker", "Woodworker", "Writer", "X-Ray Technician", "Yoga Instructor",
    "Youth Counselor", "Zoologist", "Zumba Instructor"
}

function getRandomJob()
    math.randomseed(os.time())       
    local index = math.random(#jobs) 
    return jobs[index]               
end
